version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - "> 2.11.505, < 2.12"
  - dependency-name: rubocop-rails_config
    versions:
    - 1.2.2
    - 1.3.0
    - 1.3.1
    - 1.3.2
    - 1.3.3
    - 1.3.4
    - 1.4.0
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.7.0
    - 1.7.2
    - 1.7.3
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: webmock
    versions:
    - 3.11.2
    - 3.12.0
    - 3.12.1
  - dependency-name: elasticsearch
    versions:
    - 7.10.1
    - 7.11.1
    - 7.11.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
